# Generated by Django 5.1.4 on 2025-01-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_options_alter_post_options_and_more'),
        ('products', '0002_alter_category_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='products.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='skin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='products.skintype'),
        ),
    ]
