# Generated by Django 5.1.4 on 2025-01-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size_g',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size_ml',
        ),
    ]
